version: '3.1'
services:
  ui:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /Users/jamesrichards/Desktop/Coding/Projects/Typescript/Bug-Tracker/frontend:/app
volumes:
  ui: