version: '3.1'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: 
      context: ./backend
    ports: 
      - 8080:8080
  ui:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    ports:
      - 8000:80

volumes:
  db-data: