version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - api-data:/var/lib/postgresql/datadocker
  api:
    build: .
    ports: 
      - 3000:3000
    depends_on: 
      - db
    volumes:
      - api-data
volumes:
  api-data:
