version: '3.1'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    ports: 
      - 8080:8080
    volumes:
      - api-data:/app/public/images/

volumes:
  db-data:
  api-data: 